stages:
  - build
  - deploy

variables:
# System environment

  # Common parameters for the 'make' during CI tests
  MAKEFLAGS: "-j5 --no-keep-going"

# GitLab-CI environment

  # more attempts for more robust
  GET_SOURCES_ATTEMPTS: "10"
  ARTIFACT_DOWNLOAD_ATTEMPTS: "10"

  # We use get_sources.sh script to fetch the submodules and/or re-fetch the repo
  # if it was corrupted (if submodule update fails this can happen)
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  MDF_PATH: "$CI_PROJECT_DIR"
  IDF_PATH: "$CI_PROJECT_DIR/esp-idf"

before_script:
  - export PATH="/opt/xtensa-esp32-elf/bin:$PATH"
  - export PATH="/opt/esp32ulp-elf-binutils/bin:$PATH"
  - export PATH="$MDF_PATH/esp-idf/tools:$PATH"
  # add gitlab ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # replace submodule esp-idf to internal repository to speedup cloning
  - sed -i "s%https://github.com/espressif/esp-idf.git%${GITLAB_SSH_SERVER}/idf/esp-idf.git%" .gitmodules
  # replace submodule Adafruit-GFX-Library to internal repository to speedup cloning
  - sed -i "s%https://github.com/adafruit/Adafruit-GFX-Library.git%${GITLAB_SSH_SERVER}/zzchen/adafruit-gfx-library.git%" .gitmodules
  - git submodule update --init --recursive
  - source esp-idf/tools/ci/setup_python.sh
  # (the same regular expressions are used to set these are used in 'only:' sections below
  - source esp-idf/tools/ci/configure_ci_environment.sh

build_template_make: &build_template
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env$BOT_DOCKER_IMAGE_TAG
  tags:
    - build
  variables:
    ARTIFACTS_NAME: "default"
    DEFAULT_CONFIG: ""
    BATCH_BUILD: "1"
    V: "0"
  script:
    - ./tools/ci/build_examples_make.sh examples/get-started
    - ./tools/ci/build_examples_make.sh examples/function_demo/mcommon
    - ./tools/ci/build_examples_make.sh examples/function_demo/mconfig
    - ./tools/ci/build_examples_make.sh examples/function_demo/mdebug
    - ./tools/ci/build_examples_make.sh examples/function_demo/mupgrade
    - ./tools/ci/build_examples_make.sh examples/function_demo/mwifi/console_test
    - ./tools/ci/build_examples_make.sh examples/function_demo/mwifi/mqtt_example
    - ./tools/ci/build_examples_make.sh examples/function_demo/mwifi/no_router
    - ./tools/ci/build_examples_make.sh examples/function_demo/mwifi/root_on_ethernet
    - ./tools/ci/build_examples_make.sh examples/function_demo/mwifi/router
    - ./tools/ci/build_examples_make.sh examples/development_kit/light
    - ./tools/ci/build_examples_make.sh examples/development_kit/button
#   - ./tools/ci/build_examples_make.sh examples/development_kit/sense  sense can not build by GNU make
    - ./tools/ci/build_examples_make.sh examples/development_kit/buddy
    - ./tools/ci/build_examples_make.sh examples/aliyun_linkkit/get-started
    - ./tools/ci/build_examples_make.sh examples/aliyun_linkkit/mesh-with-aliyun

build_template_cmake: &build_template
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env$BOT_DOCKER_IMAGE_TAG
  tags:
    - build
  variables:
    ARTIFACTS_NAME: "default"
    DEFAULT_CONFIG: ""
    BATCH_BUILD: "1"
    V: "0"
  script:
    - ./tools/ci/build_examples_cmake.sh examples/get-started
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mcommon
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mconfig
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mdebug
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mupgrade
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mwifi/console_test
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mwifi/mqtt_example
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mwifi/no_router
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mwifi/root_on_ethernet
    - ./tools/ci/build_examples_cmake.sh examples/function_demo/mwifi/router
    - ./tools/ci/build_examples_cmake.sh examples/development_kit/light
    - ./tools/ci/build_examples_cmake.sh examples/development_kit/button
    - ./tools/ci/build_examples_cmake.sh examples/development_kit/sense
    - ./tools/ci/build_examples_cmake.sh examples/development_kit/buddy
    - ./tools/ci/build_examples_cmake.sh examples/aliyun_linkkit/get-started
    - ./tools/ci/build_examples_cmake.sh examples/aliyun_linkkit/mesh-with-aliyun

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v/
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  before_script:
    - echo "skip default before_script"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-mdf.git
    # What the next line of script does: goes through the list of refs for all branches we push to github,
    # generates a snippet of shell which is evaluated. The snippet checks CI_BUILD_REF against the SHA
    # (aka objectname) at tip of each branch, and if any SHAs match then it checks out the local branch
    # and then pushes that ref to a corresponding github branch
    #
    # NB: In gitlab 9.x, CI_BUILD_REF was deprecated. New name is CI_COMMIT_REF. If below command suddenly
    # generates bash syntax errors, this is probably why.
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_BUILD_REF == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)


# If you want to add new build example jobs, please add it into dependencies of `.example_test_template`

build_docs:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env$BOT_DOCKER_IMAGE_TAG
  tags:
    - build_docs
  artifacts:
    when: always
    paths:
      # English version of documentation
      - docs/en/doxygen-warning-log.txt
      - docs/en/sphinx-warning-log.txt
      - docs/en/sphinx-warning-log-sanitized.txt
      - docs/en/_build/html
      # Chinese version of documentation
      - docs/zh_CN/doxygen-warning-log.txt
      - docs/zh_CN/sphinx-warning-log.txt
      - docs/zh_CN/sphinx-warning-log-sanitized.txt
      - docs/zh_CN/_build/html
    expire_in: 1 mos
  script:
    - cd docs
    - ./check_lang_folder_sync.sh
    - cd en
    - make gh-linkcheck
    - make html
    - ../check_doc_warnings.sh
    - cd ../zh_CN
    - make gh-linkcheck
    - make html
    - ../check_doc_warnings.sh
